language: node_js
node_js:
  - "node"
script:
  - cd functions/ && yarn && cd ..
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn deploy; fi'
cache:
  directories:
  - .cache
  - .firebase
branches:
  only:
    - master
    - /^greenkeeper/.*$/
