title: Chase Adams
include: ["_pages"]
exclude: ["_includes/notes_graph.json"]
# You may need to change the base URL depending on your deploy configuration.
baseurl: ""
email: "me@0xcadams.com"

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension: false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

plugins:
  - jekyll-seo-tag

permalink: pretty
relative_permalinks: false

sass:
  sass_dir: _sass
  style: :compressed

twitter:
  username: 0xcadams
  card: summary

social:
  name: Chase Adams
  links:
    - https://twitter.com/0xcadams
    - https://github.com/0xcadams

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
